import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      // ফাইল পাথ: app/layout.tsx
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'All In One Reborn | Live Sports',
  description: 'Premium streaming hub for live sports and TV.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        {/* 💰 Adsterra Popunder */}
        <Script 
          src="https://momrollback.com/d6/33/75/d63375da536c367103a4664c302a2101.js" 
          strategy="lazyOnload" 
        />
        
        {/* 💰 Adsterra Social Bar */}
        <Script 
          src="https://momrollback.com/0c/d5/88/0cd588cbd2e534cc84cf309218b813ee.js" 
          strategy="lazyOnload" 
        />
      </body>
    </html>
  )
}

      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
