// ফাইল পাথ: app/watch/[id]/page.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import { useParams } from 'next/navigation';
import Artplayer from 'artplayer';
import Hls from 'hls.js';
import Link from 'next/link';

export default function WatchPage() {
  const params = useParams();
    const shortId = params.id as string;
      const playerRef = useRef<HTMLDivElement>(null);
        
          const [streamData, setStreamData] = useState<any>(null);
            const [loading, setLoading] = useState(true);
              const [errorMsg, setErrorMsg] = useState('');
                
                  // 🎯 আপনার টেলিগ্রাম বটের ইউজারনেম এখানে দিন (যেমন: aiorbd_bot)
                    const TELEGRAM_BOT_USERNAME = "ratulnotific_bot"; 

                      useEffect(() => {
                          // API থেকে স্ট্রিম এবং হেডার্স ফেচ করা
                              fetch(`/api/watch/${shortId}`)
                                    .then(res => res.json())
                                          .then(data => {
                                                  if (data.success) setStreamData(data);
                                                          else setErrorMsg('এই স্ট্রিমটি আর সচল নেই বা মুছে ফেলা হয়েছে!');
                                                                  setLoading(false);
                                                                        })
                                                                              .catch(() => {
                                                                                      setErrorMsg('সার্ভার থেকে ডাটা আনতে সমস্যা হয়েছে!');
                                                                                              setLoading(false);
                                                                                                    });
                                                                                                      }, [shortId]);

                                                                                                        useEffect(() => {
                                                                                                            if (!streamData || !playerRef.current) return;

                                                                                                                let art: Artplayer;

                                                                                                                    // 🎯 Hls.js কনফিগারেশন (Headers Bypass)
                                                                                                                        const customHlsConfig = {
                                                                                                                              xhrSetup: function (xhr: any, url: string) {
                                                                                                                                      const { referer, origin, cookie, userAgent } = streamData.headers;
                                                                                                                                              
                                                                                                                                                      // 브라우저 (Browser) ব্লক এড়াতে কাস্টম (X-) হেডার হিসেবেও পাঠানো হচ্ছে, 
                                                                                                                                                              // যাতে আপনার CORS প্রক্সি এগুলো রিড করে আসল সার্ভারে পাঠাতে পারে।
                                                                                                                                                                      if (userAgent) xhr.setRequestHeader('X-User-Agent', userAgent);
                                                                                                                                                                              if (cookie) xhr.setRequestHeader('X-Cookie', cookie);
                                                                                                                                                                                      if (referer) xhr.setRequestHeader('X-Referer', referer);
                                                                                                                                                                                              if (origin) xhr.setRequestHeader('X-Origin', origin);

                                                                                                                                                                                                      // সাধারণ হেডার (যদি ব্রাউজার সাপোর্ট করে)
                                                                                                                                                                                                              // if (referer) xhr.setRequestHeader('Referer', referer);
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                        };

                                                                                                                                                                                                                            art = new Artplayer({
                                                                                                                                                                                                                                  container: playerRef.current,
                                                                                                                                                                                                                                        url: streamData.streamUrl,
                                                                                                                                                                                                                                              title: streamData.title,
                                                                                                                                                                                                                                                    poster: streamData.logo,
                                                                                                                                                                                                                                                          volume: 0.8,
                                                                                                                                                                                                                                                                isLive: true,
                                                                                                                                                                                                                                                                      muted: false,
                                                                                                                                                                                                                                                                            autoplay: true,
                                                                                                                                                                                                                                                                                  pip: true,
                                                                                                                                                                                                                                                                                        autoSize: true,
                                                                                                                                                                                                                                                                                              autoMini: true,
                                                                                                                                                                                                                                                                                                    setting: true,
                                                                                                                                                                                                                                                                                                          fullscreen: true,
                                                                                                                                                                                                                                                                                                                theme: '#ef4444',
                                                                                                                                                                                                                                                                                                                      customType: {
                                                                                                                                                                                                                                                                                                                              m3u8: function (video, url) {
                                                                                                                                                                                                                                                                                                                                        if (Hls.isSupported()) {
                                                                                                                                                                                                                                                                                                                                                    const hls = new Hls(customHlsConfig);
                                                                                                                                                                                                                                                                                                                                                                hls.loadSource(url);
                                                                                                                                                                                                                                                                                                                                                                            hls.attachMedia(video);
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                    // 🎯 প্লেয়ার ফেইল করলে টেলিগ্রাম বটের Fallback
                                                                                                                                                                                                                                                                                                                                                                                                                hls.on(Hls.Events.ERROR, function (event, data) {
                                                                                                                                                                                                                                                                                                                                                                                                                              if (data.fatal) {
                                                                                                                                                                                                                                                                                                                                                                                                                                              art.notice.show = "⚠️ Stream Failed! Redirecting to Telegram...";
                                                                                                                                                                                                                                                                                                                                                                                                                                                              setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setErrorMsg('লাইভ স্ট্রিমটি প্লে হতে ব্যর্থ হয়েছে। নতুন লিংকের জন্য টেলিগ্রাম বটে যান!');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  art.destroy(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, 2000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else if (video.canPlayType('application/vnd.apple.mpegurl')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  video.src = url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        art.notice.show = 'Unsupported video format';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (art && art.destroy) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      art.destroy(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, [streamData]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="min-h-screen bg-slate-950 text-white flex flex-col items-center pt-10 px-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="w-full max-w-5xl bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-2xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="p-4 border-b border-slate-800 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h1 className="text-lg md:text-xl font-bold flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="w-3 h-3 bg-red-500 rounded-full animate-pulse"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {streamData ? streamData.title : 'Live Stream'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link href="/" className="text-sm bg-slate-800 hover:bg-red-600 px-3 py-1.5 rounded-lg transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ফিরে যান
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* 🎯 প্লেয়ার কন্টেইনার */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="relative aspect-video w-full bg-black flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/80 z-20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="w-12 h-12 border-4 border-red-500 border-t-transparent rounded-full animate-spin mb-3"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-slate-400">খেলার লিংক লোড হচ্ছে...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* 🎯 টেলিগ্রাম Fallback / Error UI */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {errorMsg && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="absolute inset-0 flex flex-col items-center justify-center bg-slate-900/95 z-30 p-6 text-center backdrop-blur-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-5xl mb-4">🤖</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-2xl font-bold text-red-500 mb-2">স্ট্রিমিং ব্যর্থ হয়েছে!</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-slate-300 mb-6 max-w-md">{errorMsg}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href={`https://t.me/${TELEGRAM_BOT_USERNAME}?start=${shortId}`} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="bg-[#0088cc] hover:bg-[#0077b3] text-white font-bold py-3 px-6 rounded-xl transition-all shadow-lg shadow-blue-500/30 flex items-center gap-2 animate-bounce"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span>বট থেকে নতুন লিংক নিন</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span>↗️</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Artplayer DOM Element */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {!errorMsg && <div ref={playerRef} className="w-full h-full"></div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }